### ISSUE TITLE
Inleiding

### ISSUE THREAD

**Issue by ErazerBrecht** [ArneSchoonvliet/INFSEC_ArneBart#1]
![image](https://cloud.githubusercontent.com/assets/6287467/12337954/713e328c-bb0d-11e5-99b8-2aa7b7b2a6bf.png)

Dit is een kopie uit de inleiding van het GIP dat ik samen met @SchrauwenS heb gemaakt in het jaar 2012 - 2013. De datum kan geverifieerd worden op Gitok te Kalmthout.

Ik nog Stijn hebben toestemming gegeven om deze tekst te gebruiken. Vind ik wel straf, aangezien ik jullie meerdere malen geholpen heb (MITMf???), vind ik dit straf dat je dit zonder vragen doet...

Mocht je toestemming hebben gevraagd aan het Gitok geen probleem maar ik zou deze dan graag willen zien.

Anders zal ik toch genoodzaakt moeten zijn om verdere stappen te nemen.

**Comment by ErazerBrecht** [comment]
@V4mirax 
Hij heeft een geljikaardig tekst waarop wij onze gebaseerd hebben. Dus is dit volledig ten rechte dat jullie dit gebruiken! Mijn excuses

Hierbij bedank ik Bart nog eens na al die jaar dat wij je mochten gebruiken als voorbeeld!
@ArneSchoonvliet trololo, de Stijn al beginnen lastig vallen :+1: ([Don't take the bait])(https://www.youtube.com/watch?v=OKxTH107jgs)

**Comment by V4mirax** [comment]
@ErazerBrecht 
fijn dat we er uit geraakt zijn zonder verdere stappen te moeten nemen ;)

**Comment by ErazerBrecht** [comment]
We doet nen mens zoal als hem geen goesting meer heeft om te typen :)

**Comment by SchrauwenS** [comment]
Fijn dat we er als vrienden uitkomen :p
